# .github/workflows/deploy.yml

name: ğŸš€ Deploy Blinkly API

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: ğŸ”„ Auto Deploy to Droplet via SSH Key
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Deploy over SSH using Key
        uses: appleboy/ssh-action@master
        with:
          host: 167.71.56.71
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "ğŸ“‚ Moving to backend folder"
            cd /var/www/blinkly-back-end

            echo "ğŸ“¥ Pulling latest changes"
            git reset --hard HEAD
            git pull origin main

            echo "ğŸ“¦ Installing dependencies"
            npm install

            echo "âš™ï¸ Building"
            npm run build

            echo "ğŸš€ Restarting API"
            pm2 restart blinkly-api || pm2 start dist/main.js --name blinkly-api
